version: '3'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "appversions.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/opt/appversions'
    ports:
      - '8000:8000'
