FROM python:3.7-alpine

ENV INSTALL_PATH /opt/appversions

RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH

RUN pip install pipenv
ADD Pipfile Pipfile.lock ./
RUN pipenv install --system --deploy

COPY . .
CMD gunicorn -b 0.0.0.0:8000 --access-logfile - "appversions.app:create_app()"